version: "3.9"
networks:
  milestoneNet: {}
services:
  index-container:
    build:
      context: ./indexDockerfile
      dockerfile: Dockerfile
    ports:
      - "8090:80"
    depends_on:
      - mysql-container
    networks:
      - milestoneNet
  mysql-container:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 2000
      MYSQL_DATABASE: milestone1db
    volumes:
       - /var/lib/mysql:/var/lib/mysql
    networks:
      - milestoneNet
