version: "3.9"
networks:
  milestoneNet: {}
services:
  webserver:
    container_name: contapa2-m1-CNK
    build:
      context: ./phpDockerfile
      dockerfile:  Dockerfile
    depends_on:
      - db
    volumes:
      - ./phpDockerfile:/var/www/html/
    ports:
      - 8085:80
    networks:
      - milestoneNet
  db:
    container_name: contsql-m1-CNK
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 2000
      MYSQL_DATABASE: milestone1db
    volumes:
       - ./db-data:/var/lib/mysql
    networks:
      - milestoneNet
  phpmyadmin:
    container_name: phpmyadmin
    image: 'phpmyadmin:latest'
    depends_on:
        - db
    ports:
       - "8060:80"
    restart: always
    networks:
       - milestoneNet
    environment:
      - PMA_ARBITRARY=1
