version: "3.9"
networks:
  milestoneNet: {}
services:
  php-container:
    build:
      context: ./phpDockerfile
      dockerfile:  Dockerfile
    depends_on:
      - mysql-container
    volumes:
      - ./phpDockerfile:/var/www/html/
    ports:
      - 8000:80
    networks:
      - milestoneNet
  mysql-container:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 2000
      MYSQL_DATABASE: milestone1db
    volumes:
       - ./db-data:/var/lib/mysql
    networks:
      - milestoneNet
  phpmyadmin:
    image: 'phpmyadmin:latest'
    depends_on:
        - mysql-container
    ports:
       - "8060:80"
    restart: always
    networks:
       - milestoneNet
    environment:
      - PMA_ARBITRARY=1
