version: "3.9"
networks:
  milestoneNet: {}
services:
  index-container:
    build:
      context: ./indexDockerfile
      dockerfile: Dockerfile
    ports:
      - "8090:80"
    depends_on:
      - mysql-container
    networks:
      - milestoneNet
  php-container:
    build:
      context: ./phpDockerfile
      dockerfile:  Dockerfile
    depends_on:
      - mysql-container
    volumes:
      - ./phpDockerfile:/var/www/html/
    ports:
      - 8000:80
  mysql-container:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 2000
      MYSQL_DATABASE: milestone1db
    volumes:
       - /db-data:/var/lib/mysql
    networks:
      - milestoneNet
